PfsTargetSpectra: use 64-bit pointers for fluxTable
pfsCoadd files are getting too big, so we're getting:
    ValueError: The heapsize limit for 'P' format has been reached. Please consider using the 'Q' format for your file.
The fluxTable is the largest HDU, so that's probably where
this is coming from. Switching to Q arrays instead of P arrays
will give us a larger size limit.